version: '3.1'
services:
    redis:
        image: redis:alpine
        container_name: b2b-order-management-redis
        ports:
            - "6379:6379"
        networks:
            - app-network

    mysql:
        container_name: b2b-order-management-mysql
        image: 'mysql:8.0'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - '22002:3306'
        networks:
            - app-network
    nginx:
        image: 'nginx:alpine'
        container_name: b2b-order-management-nginx
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '22000:80'
        depends_on:
            - php-fpm
        networks:
            - app-network

    php-fpm:
        build: ./docker/php-fpm
        container_name: b2b-order-management-php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/cli/conf.d/99-overrides.ini'
        networks:
            - app-network

networks:
    app-network:
